sudo rm -r code/myfaculty/associates/migrations/0*.py
sudo rm -r code/myfaculty/curricula/migrations/0*.py
sudo rm -r code/myfaculty/leaves/migrations/0*.py
sudo rm -r code/myfaculty/myprofile/migrations/0*.py
sudo rm -r code/myfaculty/phdapplications/migrations/0*.py
sudo rm -r code/myfaculty/projects/migrations/0*.py
sudo rm -r code/myfaculty/theses/migrations/0*.py
sudo rm -r code/myfaculty/timesheets/migrations/0*.py
sudo rm -r code/myfaculty/scopes/migrations/0*.py
sudo rm -r code/myfaculty/rfs/migrations/0*.py
sudo rm -r code/myfaculty/phdstuds/migrations/0*.py