"""
Django settings for myfaculty project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import ldap
from django_auth_ldap.config import LDAPSearch
import os
from django.core.exceptions import ImproperlyConfigured
from myprofile import emails

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get('DEBUG') == 'True'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-key-change-me'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG is False.')

# SECURITY WARNING: don't run with debug turned on in production!
DUMMY_EMAILS = os.environ.get('DUMMY_EMAILS') == 'True'

if DUMMY_EMAILS:
    print('Outputing email messages to console because env variable DUMMY_EMAILS is set to True.')

ALLOWED_HOSTS = ['myfaculty-dev.ditapps.hua.gr', 'localhost', '127.0.0.1', '10.100.59.105', '192.168.2.109', '192.168.2.10', '10.100.59.214', 'mydep.ditapps.hua.gr']
CSRF_TRUSTED_ORIGINS = ['https://mydep.ditapps.hua.gr', 'https://myfaculty-dev.ditapps.hua.gr', 'http://localhost:30100']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_TMP_EXPORT = BASE_DIR / 'media/export/tmp'

if not os.path.isdir(MEDIA_TMP_EXPORT): 
        os.makedirs(MEDIA_TMP_EXPORT)
    

STATIC_URL = '/static/'

# φάκελος που έχεις τα static αρχεία σου
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# φάκελος που θα δημιουργηθεί από collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'dal',
    'dal_select2',
    'myprofile.apps.MyprofileConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    'rest_framework',
    'rest_framework.authtoken',
    'django_recaptcha',
    'django_celery_results',
    'scopes',
    'api',
    'rfs',
    'associates',
    'curricula',
    'export',
    'projects',
    'leaves',
    'timesheets',
    'theses',
    'phdapplications',
    'phdstuds',
    'course_recognition'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myprofile.middleware.DevServerMiddleware',
]

ROOT_URLCONF = 'myfaculty.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myfaculty.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    "myfaculty.auth.CustomAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_REDIRECT_URL='/'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'el'

TIME_ZONE = 'Europe/Athens'

USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("el", "Greek"),
    ("en", "English"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

#USE_L10N = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATE_FORMAT = '%d/%m/%Y'
DATE_INPUT_FORMATS = ['%d/%m/%Y']


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"django_auth_ldap": {"level": "DEBUG", "handlers": ["console"]}},
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
	'USER': os.environ.get('POSTGRES_USER'),
	'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': '',
    }
}

# LDAP options
AUTH_LDAP_SERVER_URI = os.environ.get('AUTH_LDAP_SERVER_URI')
AUTH_LDAP_BIND_DN = os.environ.get('AUTH_LDAP_BIND_DN')
AUTH_LDAP_BIND_PASSWORD = os.environ.get('AUTH_LDAP_BIND_PASSWORD')
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "dc=hua,dc=gr", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
)
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email":"email"
}
AUTH_LDAP_START_TLS = True
AUTH_LDAP_GLOBAL_OPTIONS ={
    ldap.OPT_X_TLS_REQUIRE_CERT : ldap.OPT_X_TLS_NEVER 
}

# Custom auth backend
INTERNAL_DOMAIN = 'hua.gr'

# docx templates
ECTS_GR_TEMPLATE = 'ects_gr'
ECTS_EN_TEMPLATE = 'ects_en'
PROPOSAL_TEMPLATE = 'proposal'
LEAVE_TEMPLATE = 'leave_template'
PHD_APPLICATION_TEMPLATE = 'phdapplication'

# Mailer settings
ALWAYS_NOTIFY = 'ditdean@hua.gr,itsec@hua.gr'
DEAN_EMAIL = 'thkam@hua.gr'
EMAIL_PLATFORM_URL = 'https://mydep.ditapps.hua.gr'

# Django SMTP configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@hua.gr')


# SIS settings
SIS_KEYCLOAK_TOKEN_URL = os.environ.get('SIS_KEYCLOAK_TOKEN_URL')
SIS_CLIENT_ID = os.environ.get('SIS_CLIENT_ID')
SIS_USER_NAME = os.environ.get('SIS_USER_NAME')
SIS_PASSWD = os.environ.get('SIS_PASSWD')

# Password complexity for user signup
UPPERCASE_MIN = 1
LOWERCASE_MIN = 1
DIGITS_MIN = 1
SPECIAL_CHARACTERS_MIN = 2
MIN_LENGTH = 8
#PASSWORD_SPECIAL_CHARS = r'[!@#\$%\^&\*\(\)_\+\-=\[\]\{\};:\"",\.<>\/\?\\\|~]'
PASSWORD_SPECIAL_CHARS = '{}!@#$%^&*()-+'

# User registration options
MAX_AGE = 32000 # number seconds one time registration links are active 
REGISTRATION_MESSAGE = emails.USER_REGISTRATION_MESSAGE
REGISTRATION_SUBJECT = 'Activate your account / Ενεργοποιήση του Λογαριασμού σας'

FORGOT_PASSWORD_BODY = emails.USER_FORGOT_PASSWORD_BODY
FORGOT_PASSWORD_SUBJECT = 'Password Reset / Επαναφορά κωδικού'

# reCAPTCHA settings
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', 'dummy-public-key')
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', 'dummy-private-key')

# Settings for reference letter invitations
INVITATION_REFERENCE_MAX_AGE = 30 # Number of days that the invitation links are valid
INVITATION_REFERENCE_MAX_AGE_SECS = INVITATION_REFERENCE_MAX_AGE * 24 * 60 * 60

# INVITATION_REFERENCE_BODY = """

# <p> Dear Sir or Madam </p>,

# <p> The applicant with the following details </p>
# <p> First name: <b> {name} </b> </p>
# <p> Last name: <b> {surname} </b> </p>

#     has submitted an application to the PhD program of the Department
#     <b> {department_en} - {university_en} </b>

#     under the call entitled:
#     {call_title_en} 

#     and has indicated you as the contact person for a reference letter for their application.
#     You may submit your reference letter for the applicant at the following link:
#     {url}

# Αγαπητέ Κύριε ή αγαπητή Κυρία,

#   Ο υποψήφιος με τα παρακάτω στοιχεία 
#   Όνομα: {name}
#   Επώνυμο: {surname}
  
#   έχει υποβάλλει αίτηση στο πρόγραμμα διδακτορικών σπουδών του Τμήματος
#   {department_gr} - {university_gr}
  
#   στην πρόσκληση με τίτλο:
#   {call_title_gr}

#   και έχει υποδείξει εσάς ως σημείο επαφής για συστατική επιστολή για την αίτηση του. 
#   Μπορείτε να υποβάλλετε την συστατική επιστολή σας για τον υποψήφιο στο παρακάτω σύνδεσμο:
#   {url}

# """

INVITATION_DEPARTMENT_GR = 'Πληροφορικής και Τηλεματικής'
INVITATION_UNIVERSITY_GR = 'Χαροκόπειο Πανεπιστημίο'
INVITATION_DEPARTMENT_EN = 'Informatics and Telematics'
INVITATION_UNIVERSITY_EN = 'Harokopio University'

# Reset password
PASSWORD_RESET_LINK_AGE = 3600

# development server keywords
DEV_SERVER_KEYWORDS = ['dev', 'localhost']

CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"

# Budibase key used for migrations:
BUDI_KEY = os.environ.get('BUDI_KEY')

JAZZMIN_SETTINGS = {
    "site_title": "Σύστημα Αναγνώρισης Μαθημάτων",
    "site_header": "Σύστημα Αναγνώρισης Μαθημάτων",
    "site_brand": "Αναγνώριση Μαθημάτων",
    "welcome_sign": "Καλώς ήρθατε στο Σύστημα Αναγνώρισης Μαθημάτων",
    "copyright": "Χαροκόπειο Πανεπιστήμιο",
    "search_model": [],
    "topmenu_links": [],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "curricula.Course": "fas fa-book",
        "curricula.StudyProgram": "fas fa-graduation-cap",
    },
}
