ΜΙΧΑΛΑΚΕΛΗΣ,michalak
ΒΑΜΒΑΚΑΡΗ,mvamv
ΑΝΑΓΝΩΣΤΟΠΟΥΛΟΣ,dimosthe
ΔΙΟΥ,cdiou
ΖΟΜΠΑΚΗΣ,zompakis
ΤΣΕΡΠΕΣ,tserpes
ΜΠΑΡΔΑΚΗ,cleobar
ΜΙΧΑΗΛ Π.,pmichael
ΧΑΡΑΛΑΜΠΙΔΗΣ,acharal
ΜΙΧΑΗΛ,michail
ΚΟΥΣΙΟΥΡΗΣ,gkousiou
ΔΗΜΗΤΡΑΚΟΠΟΥΛΟΣ,gdimitra
ΡΙΖΟΜΙΛΙΩΤΗΣ,prizomil
ΒΑΡΛΑΜΗΣ,varlamis
ΣΟΦΙΑΝΟΠΟΥΛΟΥ,csofian
ΣΤΑΜΑΤΗ,teta
ΤΣΑΔΗΜΑΣ,tsadimas
ΚΑΜΑΛΑΚΗΣ,thkam
ΛΙΩΤΟΥ,eliotou
ΑΝΔΡΙΚΟΣ,candrikos
ΔΑΛΑΚΑΣ,vdalakas
ΠΑΠΑΔΟΠΟΥΛΟΣ,g.th.papadopoulos
ΔΕΔΕ,gdede
ΦΙΛΙΟΠΟΥΛΟΥ,evanelf
ΑΝΤΩΝΟΠΟΥΛΟΥ,
ΓΑΣΠΑΡΙΝΑΤΟΥ,alegas
ΕΥΘΥΜΙΟΥ,vefthym
ΓΚΟΥΛΗΣ,