# Generated by Django 6.0.4 on 2026-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecognitionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_part', models.CharField(choices=[('COMPATIBLE', 'Διδάχθηκε σε συμβατό επίπεδο'), ('NOT_COMPATIBLE', 'Δεν διδάχθηκε σε συμβατό επίπεδο'), ('NOT_APPLICABLE', 'Δεν εφαρμόζεται')], max_length=20, verbose_name='Θεωρητικό μέρος')),
                ('laboratory_part', models.CharField(choices=[('COMPATIBLE', 'Διδάχθηκε σε συμβατό επίπεδο'), ('NOT_COMPATIBLE', 'Δεν διδάχθηκε σε συμβατό επίπεδο'), ('NOT_APPLICABLE', 'Δεν εφαρμόζεται')], default='NOT_APPLICABLE', max_length=20, verbose_name='Εργαστηριακό μέρος')),
                ('approval', models.BooleanField(default=False, verbose_name='Εγκρίνεται')),
                ('grade', models.FloatField(blank=True, null=True, verbose_name='Βαθμός αναγνώρισης')),
                ('comments', models.TextField(blank=True, verbose_name='Σχόλια καθηγητή')),
                ('submitted_by_secretariat', models.BooleanField(default=False, verbose_name='Συμπληρώθηκε από γραμματεία')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Εισήγηση αναγνώρισης μαθήματος',
                'verbose_name_plural': 'Εισηγήσεις αναγνώρισης μαθημάτων',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseRecognitionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_recognized_course', models.CharField(max_length=255, verbose_name='Τίτλος αναγνωριζόμενου μαθήματος')),
                ('title_original_course', models.CharField(max_length=255, verbose_name='Τίτλος μαθήματος που έχει διδαχθεί στο άλλο πρόγραμμα σπουδών')),
                ('institution', models.CharField(max_length=255, verbose_name='Ίδρυμα')),
                ('school', models.CharField(max_length=255, verbose_name='Σχολή')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Τμήμα')),
                ('instructors', models.CharField(max_length=255, verbose_name='Διδάσκοντες')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Έτος στο οποίο διδάχθηκε')),
                ('academic_semester', models.CharField(choices=[('WINTER', 'Χειμερινό'), ('SPRING', 'Εαρινό')], max_length=20, verbose_name='Εξάμηνο στο οποίο διδάχθηκε')),
                ('grade_theory', models.FloatField(verbose_name='Βαθμός θεωρητικής εξέτασης')),
                ('grade_lab', models.FloatField(blank=True, null=True, verbose_name='Βαθμός εργαστηριακής εξέτασης')),
                ('average_grade', models.FloatField(verbose_name='Μέσος όρος βαθμολογίας')),
                ('hours_theory', models.IntegerField(verbose_name='Αριθμός ωρών ανά εβδομάδα - θεωρία')),
                ('hours_lab', models.IntegerField(blank=True, null=True, verbose_name='Αριθμός ωρών ανά εβδομάδα - εργαστήριο')),
                ('description', models.TextField(verbose_name='Περιγραφή μαθήματος')),
                ('url', models.URLField(blank=True, verbose_name='URL μαθήματος')),
                ('course_description_file', models.FileField(upload_to='course_recognition/course_descriptions/', verbose_name='Περιγραφή μαθήματος - αρχείο')),
                ('transcript_file', models.FileField(upload_to='course_recognition/transcripts/', verbose_name='Αναλυτική βαθμολογία - αρχείο')),
                ('degree_file', models.FileField(upload_to='course_recognition/degrees/', verbose_name='Πτυχίο - αρχείο')),
                ('comments', models.TextField(blank=True, verbose_name='Σχόλια αιτούντα')),
                ('protocol_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός πρωτοκόλλου')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Υποβλήθηκε'), ('UNDER_REVIEW', 'Υπό εξέταση'), ('APPROVED', 'Εγκρίθηκε'), ('REJECTED', 'Απορρίφθηκε'), ('WITHDRAWN', 'Αποσύρθηκε / Μη ενεργή')], default='SUBMITTED', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Αίτηση αναγνώρισης μαθήματος',
                'verbose_name_plural': 'Αιτήσεις αναγνώρισης μαθημάτων',
                'ordering': ('-created_at',),
            },
        ),
    ]
