# Generated by Django 6.0.4 on 2026-04-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_recognition', '0001_initial'),
        ('curricula', '0001_initial'),
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecognitionrecommendation',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_recognition_recommendations', to='myprofile.staffmember', verbose_name='Καθηγητής'),
        ),
        migrations.AddField(
            model_name='courserecognitionrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_requests', to='curricula.course', verbose_name='Μάθημα προς αναγνώριση'),
        ),
        migrations.AddField(
            model_name='courserecognitionrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_recognition_requests', to='myprofile.student', verbose_name='Φοιτητής'),
        ),
        migrations.AddField(
            model_name='courserecognitionrecommendation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='course_recognition.courserecognitionrequest', verbose_name='Αίτηση αναγνώρισης'),
        ),
    ]
