# Generated by Django 6.0.4 on 2026-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_recognition', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserecognitionrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='courserecognitionrequest',
            name='title_recognized_course',
        ),
        migrations.AddField(
            model_name='courserecognitionrequest',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Ονοματεπώνυμο'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courserecognitionrequest',
            name='academic_year',
            field=models.CharField(choices=[('1', '1ο'), ('2', '2ο'), ('3', '3ο'), ('4', '4ο'), ('5', '5ο')], max_length=1, verbose_name='Έτος στο οποίο διδάχθηκε'),
        ),
        migrations.AlterField(
            model_name='courserecognitionrequest',
            name='course',
            field=models.CharField(default=1, max_length=255, verbose_name='Τίτλος μαθήματος προς αναγνώριση'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courserecognitionrequest',
            name='hours_lab',
            field=models.FloatField(blank=True, null=True, verbose_name='Αριθμός ωρών ανά εβδομάδα - εργαστήριο'),
        ),
        migrations.AlterField(
            model_name='courserecognitionrequest',
            name='hours_theory',
            field=models.FloatField(verbose_name='Αριθμός ωρών ανά εβδομάδα - θεωρία'),
        ),
    ]
