# Generated by Django 6.0.4 on 2026-04-26 18:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_gr', models.CharField(max_length=20)),
                ('code_en', models.CharField(max_length=20)),
                ('semester', models.FloatField()),
                ('title_gr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('weekly_hours', models.FloatField(blank=True, null=True)),
                ('weekly_lab_hours', models.FloatField(blank=True, null=True)),
                ('ects_credits', models.FloatField(null=True)),
                ('type_gr', models.CharField(blank=True, max_length=100)),
                ('type_en', models.CharField(blank=True, max_length=100)),
                ('prequesites_gr', models.TextField(blank=True, null=True)),
                ('prequesites_en', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('language_gr', models.CharField(blank=True, max_length=100)),
                ('language_en', models.CharField(blank=True, max_length=100)),
                ('offered_erasmus', models.BooleanField(blank=True, default=False, null=True)),
                ('outcomes_gr', models.TextField(blank=True, null=True)),
                ('outcomes_en', models.TextField(blank=True, null=True)),
                ('skills_gr', models.TextField(blank=True, null=True)),
                ('skills_en', models.TextField(blank=True, null=True)),
                ('content_gr', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('delivery_gr', models.CharField(blank=True, max_length=200)),
                ('delivery_en', models.CharField(blank=True, max_length=200)),
                ('evaluation_gr', models.TextField(blank=True, null=True)),
                ('evaluation_en', models.TextField(blank=True, null=True)),
                ('ict_gr', models.TextField(blank=True, null=True)),
                ('ict_en', models.TextField(blank=True, null=True)),
                ('bibliography_gr', models.TextField(blank=True, null=True)),
                ('bibliography_en', models.TextField(blank=True, null=True)),
                ('journals', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('required_math', models.TextField(blank=True, null=True)),
                ('required_lab', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, null=True)),
                ('elective', models.BooleanField(null=True)),
                ('hours_lecturing', models.FloatField(blank=True, null=True)),
                ('hours_lab', models.FloatField(blank=True, null=True)),
                ('hours_study', models.FloatField(null=True)),
                ('hours_project', models.FloatField(null=True)),
                ('hours_lab_prep', models.FloatField(null=True)),
                ('hours_total', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('title_en', models.CharField(max_length=100)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('title_en', models.CharField(max_length=100)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('title_en', models.CharField(max_length=100)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('Προπτυχιακό', 'Προπτυχιακό'), ('Μεταπτυχιακό', 'Μεταπτυχιακό'), ('Διδακτορικό', 'Διδακτορικό'), ('Μεταδιδακτορικό', 'Μεταδιδακτορικό'), ('´Άλλο', '´Άλλο')], max_length=100)),
                ('sis_code', models.CharField(blank=True, choices=[('550', 'Προπτυχιακό'), ('1550', 'ΠΜΣ Πληροφορική και Τηλεματική'), ('1556', 'ΠΜΣ Εφαρμοσμένη Πληροφορική'), ('1557', 'ΠΜΣ Επιστήμη των Υπολογιστών και Πληροφορική'), ('1560', 'Προηγμένες Τεχνολογίες Πληροφορικής και Εφαρμογές')], null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('has_thesis', models.BooleanField(default=True, null=True)),
                ('thesis_semesters', models.IntegerField(default=2, null=True)),
                ('thesis_report_semesters', models.IntegerField(default=1, null=True)),
                ('thesis_has_report', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TitleStrMixin, models.Model),
        ),
    ]
