# Generated by Django 6.0.4 on 2026-04-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0001_initial'),
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_to',
            field=models.ManyToManyField(to='myprofile.staffmember'),
        ),
        migrations.AddField(
            model_name='director',
            name='staffmember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember'),
        ),
        migrations.AddField(
            model_name='school',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.school'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department'),
        ),
        migrations.AddField(
            model_name='director',
            name='programs',
            field=models.ManyToManyField(to='curricula.studyprogram'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.studyprogram'),
        ),
    ]
