# Generated by Django 6.0.4 on 2026-04-26 18:03

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_secreteriat', 'Is a secreteriat user'),),
            },
        ),
        migrations.CreateModel(
            name='DoctorateApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200, null=True)),
                ('given_name', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('secondary_email', models.EmailField(max_length=254, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('ssn', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Άρρεν'), ('F', 'Θηλυ'), ('O', 'Άλλο')], max_length=1, null=True)),
                ('home_address_street', models.CharField(blank=True, max_length=70, null=True)),
                ('home_address_no', models.IntegerField(blank=True, null=True)),
                ('home_address_po_box', models.CharField(blank=True, max_length=30, null=True)),
                ('home_address_city', models.CharField(blank=True, max_length=70, null=True)),
                ('home_address_country', models.CharField(blank=True, default='Ελλάδα', max_length=70, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('work_address_street', models.CharField(default='Ομήρου', max_length=70, null=True)),
                ('work_address_no', models.CharField(default='9', max_length=10, null=True)),
                ('work_address_po_box', models.CharField(default='17778', max_length=30, null=True)),
                ('work_address_city', models.CharField(default='Αθήνα', max_length=70, null=True)),
                ('work_address_country', models.CharField(default='Ελλάδα', max_length=70, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.studyprogram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('given_name_en', models.CharField(max_length=50, null=True)),
                ('surname_en', models.CharField(max_length=70, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('display_name_full', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('is_internal', models.BooleanField(default=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('can_apply_for_phd', models.BooleanField(default=False, null=True)),
                ('can_review_phd_apps', models.BooleanField(default=True, null=True)),
                ('can_post_theses', models.BooleanField(default=True, null=True)),
                ('internal_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department')),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.personalinfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.PersonStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('display_name_full', models.CharField(blank=True, max_length=200, null=True)),
                ('is_phd_student', models.BooleanField(default=False, null=True)),
                ('is_postdoc', models.BooleanField(default=False, null=True)),
                ('card_no', models.CharField(blank=True, max_length=40, null=True)),
                ('seat_no', models.CharField(blank=True, max_length=40, null=True)),
                ('office_no', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('days_per_week', models.IntegerField(blank=True, null=True)),
                ('contract', models.BooleanField(blank=True, null=True)),
                ('project_contract', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.personalinfo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.staffmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=70, null=True)),
                ('semester', models.IntegerField(null=True)),
                ('reg_num', models.CharField(max_length=70, null=True)),
                ('display_name', models.CharField(max_length=200, null=True)),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.personalinfo')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.studyprogram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
